### ISSUE TITLE
Can't publish due to unexpected java/gradle error

### ISSUE THREAD

**Issue by sairope** [AppLovin/AppLovin-MAX-AIR#2]
I'm getting 'unable to run java' and 'gradle too lfailed' errors when I'm trying to publish the app both on AIR SDK 33 and 50.2.1.1.

Here's a printscreen:

https://i.imgur.com/UYhNAl7.jpg

Could this be cause by lacking a library. You're only importing applovin ane in your example and documentation.

**Comment by santoshbagadi** [comment]
@sairope , it seems like you are missing the `network_security_config.xml` file. If you don't need any custom [Network Security configuration](https://developer.android.com/training/articles/security-config) for your app, you can just remove it from the `manifestAdditions` of your app. 

If you need custom network security config, you would need to create a `network_security_config.xml` with your settings and add it to your applications resources folder under `xml`.

**Comment by sairope** [comment]
Thanks, this works and the app's getting compiled but now I have another problem. MAX Mediation Debuger's showing an invalid integration of AppLovin due to lack of _com.google.android.gms:play-services-ads-identifier_. I couldn't find this ANE anywhere on your website or in your github repo.

https://i.imgur.com/VKYJZf4.jpg

I believe this is the reason I can't get banner ads to be displayed. I've added my device as a test device, but I'm actually seeing real interstitial and reward ads in your app. I'm not sure if this is how things are supposed to be, or is it caused by the lack of google play ad identifier extension?

MAX Mediation Debuger's indicating that it found AdMob SDK, but it's missing an Adapter.
