### ISSUE TITLE
Is this ANE still maintained?

### ISSUE THREAD

**Issue by shaymolho** [AppLovin/AppLovin-MAX-AIR#3]
Hello @santoshbagadi, @thomasmso 
We are thinking of integrating apploving ANE to our game but wasn't sure if the ANE  is still maintained as the last commit was more than 2 years ago

**Comment by santoshbagadi** [comment]
Hi @shaymolho , the plugin is being maintained and we'll update the plugin as needed if any issues arise.

**Comment by shaymolho** [comment]
Ok thanks, we'll go on with the integration and let u know if any problem
